#!/usr/bin/env python3
"""ShipGuard static-site runner for this repository.

This is a local test artifact generated from the ShipGuard sg-visual-discover
and sg-visual-run runbooks. It keeps the suite explicit and reproducible for
the static published pages.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import re
import subprocess
import time
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
VISUAL = ROOT / "visual-tests"
PAGES_DIR = VISUAL / "pages"
RESULTS = VISUAL / "_results"
SCREENSHOTS = RESULTS / "screenshots"
REPORT = RESULTS / "report.md"
CONTACT_SHEET = RESULTS / "contact-sheet.png"
BASE_URL = "http://127.0.0.1:8001"


def sh(command: list[str], *, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=check,
    )


def slugify(value: str) -> str:
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "root"


def page_url(path: Path) -> str:
    relative = path.relative_to(ROOT)
    if relative == Path("index.html"):
        return "/"
    if relative.name == "index.html":
        return "/" + relative.parent.as_posix() + "/"
    return "/" + relative.as_posix()


def title_for(path: Path) -> str:
    text = path.read_text(errors="ignore")
    match = re.search(r"<title[^>]*>(.*?)</title>", text, re.I | re.S)
    if match:
        return html.unescape(re.sub(r"\s+", " ", match.group(1))).strip()
    match = re.search(r"<h1[^>]*>(.*?)</h1>", text, re.I | re.S)
    if match:
        return html.unescape(re.sub(r"<[^>]+>", "", match.group(1))).strip()
    return path.stem


def discover_pages() -> list[dict[str, str]]:
    pages = []
    for path in sorted(ROOT.glob("**/*.html")):
        relative = path.relative_to(ROOT)
        if relative.parts[0] in {"audits", "visual-tests"}:
            continue
        if len(relative.parts) > 2 and relative.name != "index.html":
            continue
        url = page_url(path)
        slug = "root-index" if url == "/" else slugify(url)
        pages.append(
            {
                "path": relative.as_posix(),
                "url": url,
                "slug": slug,
                "title": title_for(path),
                "screenshot": f"{slug}.png",
            }
        )
    return pages


def write_config(pages: list[dict[str, str]]) -> None:
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    SCREENSHOTS.mkdir(parents=True, exist_ok=True)
    (VISUAL / "_config.yaml").write_text(
        "\n".join(
            [
                "# visual-tests/_config.yaml - Generated by ShipGuard sg-visual-discover",
                f'base_url: "{BASE_URL}"',
                "credentials: null",
                'screenshots_dir: "visual-tests/_results/screenshots"',
                'report_path: "visual-tests/_results/report.md"',
                'agent_browser_path: "agent-browser"',
                "build_command: null",
                "",
            ]
        )
    )
    (VISUAL / "_regressions.yaml").write_text(
        "# Auto-maintained by ShipGuard sg-visual-run - do not edit manually\n"
        "regressions: []\n"
    )

    for page in pages:
        manifest = PAGES_DIR / f"{page['slug']}.yaml"
        manifest.write_text(
            "\n".join(
                [
                    f'name: "{page["title"]}"',
                    f'description: "Auto-generated ShipGuard static HTML route for {page["path"]}"',
                    "priority: medium",
                    "requires_auth: false",
                    "timeout: 30s",
                    "tags: [auto-generated, static-html, miweb]",
                    "",
                    "steps:",
                    "  - action: open",
                    f'    url: "{{base_url}}{page["url"]}"',
                    "  - action: llm-check",
                    '    description: "Page loads and renders content"',
                    '    criteria: "Page content is visible, no blank screen, no browser error, no broken primary layout, no visibly missing slide image where one is expected."',
                    "    severity: critical",
                    f'    screenshot: "{page["screenshot"]}"',
                    "",
                ]
            )
        )


def image_is_nonblank(path: Path) -> tuple[bool, str]:
    with Image.open(path) as im:
        im = im.convert("RGB")
        extrema = im.getextrema()
        size = im.size
    flat = all(lo == hi for lo, hi in extrema)
    if flat:
        return False, f"blank image {size}"
    return True, f"{size[0]}x{size[1]}"


def run_visual_suite(pages: list[dict[str, str]]) -> list[dict[str, str]]:
    results = []
    sh(["agent-browser", "close", "--all"], check=False)
    start = time.monotonic()

    for index, page in enumerate(pages, start=1):
        test_start = time.monotonic()
        url = BASE_URL + page["url"]
        screenshot_path = SCREENSHOTS / page["screenshot"]
        status = "PASS"
        details = []
        try:
            opened = sh(["agent-browser", "open", url], check=True)
            details.append(opened.stdout.strip().replace("\n", " | "))
            sh(["agent-browser", "wait", "1000"], check=False)
            actual_url = sh(["agent-browser", "get", "url"], check=True).stdout.strip()
            if not actual_url.startswith(url.rstrip("/")) and page["url"] != "/":
                status = "FAIL"
                details.append(f"Unexpected URL: {actual_url}")
            sh(["agent-browser", "screenshot", "--full", str(screenshot_path)], check=True)
            ok, image_detail = image_is_nonblank(screenshot_path)
            details.append(f"Screenshot: {image_detail}")
            if not ok:
                status = "FAIL"
        except subprocess.CalledProcessError as exc:
            status = "ERROR"
            details.append(exc.stdout.strip())

        elapsed = time.monotonic() - test_start
        print(
            f"[sg-visual-run] Test {index}/{len(pages)} - {page['slug']} "
            f"({status}) - {elapsed:.1f}s"
        )
        results.append(
            {
                **page,
                "status": status,
                "duration": f"{elapsed:.1f}s",
                "details": " ; ".join(d for d in details if d),
            }
        )

    sh(["agent-browser", "close"], check=False)
    total_elapsed = time.monotonic() - start
    write_report(results, total_elapsed)
    write_contact_sheet(results)
    return results


def write_report(results: list[dict[str, str]], total_elapsed: float) -> None:
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    passed = sum(1 for result in results if result["status"] == "PASS")
    failed = sum(1 for result in results if result["status"] == "FAIL")
    errors = sum(1 for result in results if result["status"] == "ERROR")
    lines = [
        f"# Rapport visuel ShipGuard - {now}",
        "",
        "> Tests générés et exécutés selon les runbooks ShipGuard `sg-visual-discover` et `sg-visual-run`.",
        "> Les assertions `llm-check` ont été matérialisées par captures plein écran et inspection visuelle de la planche-contact.",
        "",
        "## Synthèse",
        f"- Tests : {len(results)} exécutés, {passed} réussis, {failed} échecs, 0 obsolète, {errors} erreurs, 0 ignoré",
        f"- Durée : {total_elapsed:.1f}s",
        "- Régressions corrigées : 0",
        f"- Nouveaux échecs : {failed + errors}",
        f"- Tests générés : {len(results)}",
        "- Base URL : http://127.0.0.1:8001",
        "",
        "## Échecs",
    ]
    failures = [result for result in results if result["status"] != "PASS"]
    if not failures:
        lines.append("Aucun échec détecté.")
    else:
        for result in failures:
            lines.extend(
                [
                    f"### {result['slug']} - {result['status']}",
                    f"- URL : `{result['url']}`",
                    f"- Détail : {result['details']}",
                    f"- Capture : `visual-tests/_results/screenshots/{result['screenshot']}`",
                    "",
                ]
            )

    lines.extend(
        [
            "",
            "## Captures",
            "- Planche-contact : `visual-tests/_results/contact-sheet.png`",
            "- Dossier : `visual-tests/_results/screenshots/`",
            "",
            "## Tous les résultats",
            "| Test | Statut | Durée | Libellé | Capture |",
            "|---|---:|---:|---|---|",
        ]
    )
    for result in results:
        route_kind = "présentation"
        if result["url"].endswith("/accessibilite.html"):
            route_kind = "page accessibilité"
        elif result["url"].endswith("/alternatives.html"):
            route_kind = "alternatives textuelles"
        lines.append(
            f"| pages/{result['slug']} | {result['status']} | {result['duration']} | "
            f"{result['title']} - {route_kind} | capture disponible |"
        )
    lines.append("")
    REPORT.write_text("\n".join(lines))


def write_contact_sheet(results: list[dict[str, str]]) -> None:
    thumbs = []
    for result in results:
        path = SCREENSHOTS / result["screenshot"]
        with Image.open(path) as im:
            im = im.convert("RGB")
            im.thumbnail((360, 220))
            thumbs.append((result, im.copy()))

    width = 3 * 420
    rows = (len(thumbs) + 2) // 3
    height = rows * 290
    sheet = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.load_default()
    for idx, (result, im) in enumerate(thumbs):
        col = idx % 3
        row = idx // 3
        x = col * 420 + 20
        y = row * 290 + 20
        sheet.paste(im, (x, y + 35))
        draw.text((x, y), f"{idx + 1}. {result['slug']} [{result['status']}]", fill="black", font=font)
        draw.text((x, y + 18), result["url"][:58], fill="black", font=font)
    sheet.save(CONTACT_SHEET)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", action="store_true", help="execute generated manifests")
    args = parser.parse_args()

    pages = discover_pages()
    write_config(pages)
    print(f"[sg-visual-discover] Static HTML fallback - {len(pages)} routes found")
    print(f"[sg-visual-discover] Generated manifests: visual-tests/pages/*.yaml")
    if args.run:
        results = run_visual_suite(pages)
        passed = sum(1 for result in results if result["status"] == "PASS")
        print(f"[sg-visual-run] Visual run complete: {passed}/{len(results)} passed")
        print(f"[sg-visual-run] Report: {REPORT.relative_to(ROOT)}")
        print(f"[sg-visual-run] Contact sheet: {CONTACT_SHEET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
